### ISSUE TITLE
Queue requires a config

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/appfwk#30]
The QueueConfig object is far too rigid. It was ok before we has the json inside the framework. Now that we have it we should updated QueueConfig and we should add a configure method to Queue.

**Comment by brettviren** [comment]
I have been working to understand this layer recently.

My thinking is as follows and I assume we will have a plugin/factory method.  Ie, something that may return an instance based on an "instname" (instance name) and a "typename" (some symbol with C linkage) and return it as an abstract base class.

1. `main()` CLI is told the typename of a **configuration manager**

2. `main()` calls a method on it like `get_config()`

3. this returns (at least) a `std::vector<ConfigBase>`

4. the `ConfigBase` has (at least, see below) attributes `instname` and `typename`.  These are used to look up (and possibly instantiate) the component associated with the `ConfigBase`.

5. the `ConfigBase` also has a `config` attribute which is a `std::vector<std::byte>` 

6. the `main()` code instantiates the component and calls it's `configure(std::string name, std::string typename, std::vector<std::byte> config_data)` method

7. In the body of that `configure()` method the component may deserialize the configuration data into a C++ class like `MyConfig cfg(config_data)`.

Notes:

- I refer to putting code in `main()` but better package up the above into a class ("AppManager") which `main()` uses in order to enact a more toolkit'ish approach.

- multiple configuration managers will be developed.  For example we will want one that gets configuration from a local file and another that knows how to talk to CCM.  As described, nothing depends on the implementation type of the configuration manager.

- the `MyConfig` class is **generated** from a model that defines the schema of the particular configuration for that component (it, its typename).  We will have many of these schema and the will be needed to generate other forms.

- the `MyConfig` schema is factored to exploit any commonalities between different implementations (different typenames).  Eg, all implementations of a TC finder may require some common attributes

Expert level:

- For components requiring sockets, it is at the level of `main()` where these sockets should be instantiated and bound/connected so that a discovery mechanism (such as in ZIO) can be enacted at the process level (not inside each component).  This will require that some optional configuration attributes must be exposed to `main()` at the level of `ConfigBase`.

**Comment by eflumerf** [comment]
Is this Issue still relevant?

**Comment by mroda88** [comment]
I think this issue can be closed.
