### ISSUE TITLE
DAQModule packages should not have to find_package(cetlib)

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#70]
The answer may be to have find_package(appfwk) be supported.

**Comment by jcfreeman2** [comment]
Most of the work for this issue was done on daq-buildtools' jcfreeman2/appfwk_issue70 branch, corresponding to daq-buildtools Issue 9. However, IF you've pulled that daq-buildtools code, the quick-start.sh script will construct a superproject CMakeLists.txt which sets up cetlib and folly so subprojects (like appfwk) don't have to. It's a solution which will be changed for v2, but it works.
