### ISSUE TITLE
Performance Evaluation for Queues

### ISSUE THREAD

**Issue by eflumerf** [DUNE-DAQ/appfwk#85]
We should have an integration level test that does performance evaluation for Queue implementations, including push/pop timing and rate limits, as well as fine-grained timeout evaluation (i.e. Does the Queue wait for exactly the timeout specified, within reasonable limits?).

**Comment by jcfreeman2** [comment]
A good starting point would be the `queue_IO_check` application. Implemented in ./test/queue_IO_check.cxx, it's fully documented in https://github.com/DUNE-DAQ/appfwk/wiki/Queue-testing. In a nutshell, it pushes and pops elements onto and off of a user-selectable queue with a user-selectable number of threads.

**Comment by brettviren** [comment]
This looks very useful, @jcfreeman2 

Is it correct to use first/last timestamp from the test logging shown in the wiki to estimate message rate? It gives me 0.25 MHz of transfers.  Do I have that right?

The test may also want to make the size of the "thing" sent through the queue to be set as a CLI argument.  I guess it will change the speed at some point when the payload is big enough.

Below shows rates and throughput for tests of `malloc`, `memset`, `memcpy`, `std::deque` and a few ZIO/ZeroMQ queues.  Note `std::deque` allows 7.8 MHz of 4 byte messages corresponding to the `int` payload in `queue_IO_check` and 4kB messages got a bit slower.  ZeroMQ based queues allow 5.4-7.6 MHz for 4-byte and likewise, somewhat decrease in rate for 4kB.  

Given the large discrepancy, maybe the two tests are apples and oranges?  Or, maybe I misinterpret the time values for `queue_IO_check`?  O.w. I guess there is an opportunity to speed up the appfmk queues by an order of magnitude.  

https://github.com/brettviren/zio/blob/master/test/test_speed.cpp

The output below was run on an i7-4770k.

Match 4-byte message size:

```
$ ./build/test_speed 4 1000000
[2020-07-01 12:03:44.004] [console] [info] start: 4 bytes, 1000000 count
[2020-07-01 12:03:44.014] [console] [info] malloc: 108.566 MHz, 0.434 GB/s
[2020-07-01 12:03:44.025] [console] [info] memset: 94.769 MHz, 0.379 GB/s
[2020-07-01 12:03:44.027] [console] [info] memcpy: 383.877 MHz, 1.536 GB/s
[2020-07-01 12:03:44.156] [console] [info] sync deque: 7.812 MHz, 0.031 GB/s
[2020-07-01 12:03:44.302] [console] [info] sync no free: 6.886 MHz, 0.028 GB/s
[2020-07-01 12:03:44.487] [console] [info] sync zero copy: 5.401 MHz, 0.022 GB/s
[2020-07-01 12:03:44.659] [console] [info] sync send/recv: 5.846 MHz, 0.023 GB/s
[2020-07-01 12:03:44.790] [console] [info] async send/recv: 7.612 MHz, 0.030 GB/s
```

4k message size.  The `std::deque` based queue slows down by a bit less than 2x.

```
[2020-07-01 12:20:34.267] [console] [info] start: 4096 bytes, 1000000 count
[2020-07-01 12:20:34.290] [console] [info] malloc: 42.843 MHz, 175.485 GB/s
[2020-07-01 12:20:34.386] [console] [info] memset: 10.429 MHz, 42.718 GB/s
[2020-07-01 12:20:34.432] [console] [info] memcpy: 21.779 MHz, 89.206 GB/s
[2020-07-01 12:20:34.630] [console] [info] sync deque: 5.054 MHz, 20.703 GB/s
[2020-07-01 12:20:34.788] [console] [info] sync no free: 6.332 MHz, 25.937 GB/s
[2020-07-01 12:20:35.020] [console] [info] sync zero copy: 4.326 MHz, 17.719 GB/s
[2020-07-01 12:20:35.316] [console] [info] sync send/recv: 3.376 MHz, 13.828 GB/s
[2020-07-01 12:20:36.075] [console] [info] async send/recv: 1.319 MHz, 5.403 GB/s
```

**Comment by jcfreeman2** [comment]
Thanks for the feedback. A difference between what happens in test_speed.cpp and the example I give in the queue_IO_check's wiki documentation is that in test_speed.cpp, when there's reading or writing going on, there's not another thread trying to gain access to the queue. In the queue_IO_check example, you have one thread trying to write, and one thread trying to read at the same time. So the 0.25 MHz refers to the rate at which an element can be written to _and_ read from a container, as accomplished by two threads. 

You make a good point that it would be useful if users could specify the size of the elements, rather than being stuck with integers. There's actually a couple of other improvements I'd like to make to queue_IO_check as well:

* The ability to have "read-only" runs, where the queue is initially filled as a precursor to thread(s) reading with no competing threads writing.
* Right now the default queue capacity is 2 million elements, so if you choose an `--nelements ` argument greater than 2 million, you'll need to set an argument `--capacity ` accordingly. Silly requirement, easily fixed. 
* Timing can be made more precise. Specially, rather that starting the timer, then sticking the threads on a vector and calling join on them, timing can be performed on a per-thread basis, and the start/stop times can begin/end the functions which run on the threads. 

In the next few days, when I have time, I'll file an Issue related to implementing these improvements for queue_IO_check.

**Comment by alessandrothea** [comment]
Is any additional work required for this issue or can we close it?

**Comment by jcfreeman2** [comment]
It's in a good place right now, documentation at https://github.com/DUNE-DAQ/appfwk/wiki/Queue-testing. It hasn't been used extensively since we haven't been churning out new queue types or optimizing old ones, but I've been able to demonstrate that, e.g., the Folly multiple-producer-multiple-consumer queue increasingly outperforms StdDeQueue the more threads we request at the command line (not a shocker, obviously).
